version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: effModile
      POSTGRES_USER: effModile
      POSTGRES_PASSWORD: effModile

  db:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: effModile
      POSTGRES_USER: effModile
      POSTGRES_PASSWORD: effModile
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
